# dotnet new template jobs
#
# - nuget pack templates
# - integration testing with different framework versions and tepmplate package versions

templates pack:
  stage: publish
  script:
    - 'export X_CI_VERSION=$(git describe | cut -c 2-)'
    - 'echo Publishing templates version $X_CI_VERSION'
    - 'dotnet pack RobSharper.Ros.IntegROS.ProjectTemplates.sln -c Release -o ./nuget/ -p:Version=$X_CI_VERSION'
  artifacts:
    paths:
      - 'nuget'
  tags:
    - docker-executor

.template-test:
  stage: test-templates
  script:
    - 'dotnet --list-sdks'
    - 'export X_CI_VERSION=$(git describe | cut -c 2-)'
    - 'echo Installing templates RobSharper.Ros.IntegROS.ProjectTemplates.$X_TEMPLATES_VERSION, version $X_CI_VERSION'
    - 'dotnet new -i ./nuget/RobSharper.Ros.IntegROS.ProjectTemplates.$X_TEMPLATES_VERSION.$X_CI_VERSION.nupkg'
    - 'mkdir ProjectTemplateTest'
    - 'cd ProjectTemplateTest'
    - 'echo Create new IntegROS project' 
    - '[[ ! -z "$X_FRAMEWORK_VERSION" ]] && echo Target framework: $X_FRAMEWORK_VERSION'
    - '[[ ! -z "$X_FRAMEWORK_VERSION" ]] && dotnet new integros --framework $X_FRAMEWORK_VERSION --no-restore || dotnet new integros --no-restore'
    - 'dotnet add package RobSharper.Ros.IntegROS --version $X_CI_VERSION --no-restore'
    - 'dotnet restore --configfile ../ProjectTemplates/IntegrationTests.NuGet.config'
    - 'dotnet build --no-restore'
    - 'dotnet test --no-build --verbosity normal'
  tags:
    - docker-executor


2.1 Default:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:2.1
  variables:
    X_TEMPLATES_VERSION: '2.1'
    X_FRAMEWORK_VERSION: ''

2.1 on .Net Core 2.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:2.1
  variables:
    X_TEMPLATES_VERSION: '2.1'
    X_FRAMEWORK_VERSION: 'netcoreapp2.1'

2.1 on .Net Core 3.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  variables:
    X_TEMPLATES_VERSION: '2.1'
    X_FRAMEWORK_VERSION: 'netcoreapp3.1'

2.1 on .Net 5:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    X_TEMPLATES_VERSION: '2.1'
    X_FRAMEWORK_VERSION: 'net5.0'

2.1 on .Net 6:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    X_TEMPLATES_VERSION: '2.1'
    X_FRAMEWORK_VERSION: 'net6.0'


3.1 Default:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  variables:
    X_TEMPLATES_VERSION: '3.1'
    X_FRAMEWORK_VERSION: ''

3.1 on .Net Core 2.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:2.1
  variables:
    X_TEMPLATES_VERSION: '3.1'
    X_FRAMEWORK_VERSION: 'netcoreapp2.1'

3.1 on .Net Core 3.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  variables:
    X_TEMPLATES_VERSION: '3.1'
    X_FRAMEWORK_VERSION: 'netcoreapp3.1'

3.1 on .Net 5:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    X_TEMPLATES_VERSION: '3.1'
    X_FRAMEWORK_VERSION: 'net5.0'

3.1 on .Net 6:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    X_TEMPLATES_VERSION: '3.1'
    X_FRAMEWORK_VERSION: 'net6.0'


5.0 Default:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    X_TEMPLATES_VERSION: '5.0'
    X_FRAMEWORK_VERSION: ''

5.0 on .Net Core 2.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:2.1
  variables:
    X_TEMPLATES_VERSION: '5.0'
    X_FRAMEWORK_VERSION: 'netcoreapp2.1'

5.0 on .Net Core 3.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  variables:
    X_TEMPLATES_VERSION: '5.0'
    X_FRAMEWORK_VERSION: 'netcoreapp3.1'

5.0 on .Net 5:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    X_TEMPLATES_VERSION: '5.0'
    X_FRAMEWORK_VERSION: 'net5.0'

5.0 on .Net 6:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    X_TEMPLATES_VERSION: '5.0'
    X_FRAMEWORK_VERSION: 'net6.0'


6.0 Default:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    X_TEMPLATES_VERSION: '6.0'
    X_FRAMEWORK_VERSION: ''

6.0 on .Net Core 2.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:2.1
  variables:
    X_TEMPLATES_VERSION: '6.0'
    X_FRAMEWORK_VERSION: 'netcoreapp2.1'

6.0 on .Net Core 3.1:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  variables:
    X_TEMPLATES_VERSION: '6.0'
    X_FRAMEWORK_VERSION: 'netcoreapp3.1'

6.0 on .Net 5:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    X_TEMPLATES_VERSION: '6.0'
    X_FRAMEWORK_VERSION: 'net5.0'

6.0 on .Net 6:
  extends: .template-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    X_TEMPLATES_VERSION: '6.0'
    X_FRAMEWORK_VERSION: 'net6.0'
